### ISSUE TITLE
Некорректное удаление списков задач.

### ISSUE THREAD

**Issue by Yesquero** [DenyingMad/nota-tabula-front#15]
Описание проблемы: При определенной последовательности создания списков задач удаляется не тот список, если не обновить страницу перед удалением.

Шаги для повторения:
1. Создать Эпик.
2. В дефолтный список внести одну задачу с названием "1".
3. Создать еще один список, в нем создать задачу "2".
4. Удалить список, содержащий задачу "1". Вместо списка с задачей "1" удалится список с задачей "2". Если перед удалением обновить страницу удаляется нужный список.

**Comment by DenyingMad** [comment]
Фикс #16 работает нестабильно, на мой взгляд, требуется дополнительное тестирование на разных кейсах.
@Yesquero можешь кратко пояснить, что случилось и в чем фикс?

**Comment by Yesquero** [comment]
Если в MenuItem напрямую использовать props.taskList.taskListId то id списка задач передается некорректно, то есть для нескольких списков задач он по нажатию кнопки передается один и тот-же id. Я не разобрался в чем причина и решил id доставать из якорного элемента Menu,

Это решило проблему в случае, описанном в данном issue, но я не знаю насчет других случаев, сегодня еще потестирую.
